apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-workshop
  region: us-east-1

fargateProfiles:
- name: checkout-profile
  selectors:
  - namespace: checkout
    labels:
      fargate: 'yes'
  subnets:
  - subnet-0a6820233c142ff05
  - subnet-0737f497087aa48d4
  - subnet-01bb1241ef43c9508
  podExecutionRoleARN: arn:aws:iam::839399074955:role/eks-workshop-fargate